org: entee28
app: lambda-serverless-lab
service: hello-service

provider:
  name: aws
  region: ap-southeast-1
  deploymentMethod: direct
  ecr:
    images:
      hello-service:
        uri: ${param:repo}:${param:imagetag}

functions:
  api:
    image: hello-service
    architecture: arm64
    events:
      - httpApi: "*"
