org: entee28
app: lambda-serverless-lab
service: bye-service

package:
  patterns:
    - "!node_modules/**"

provider:
  name: aws
  region: ap-southeast-1
  deploymentMethod: direct
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"
