org: entee28
app: lambda-serverless-lab
service: bye-service
frameworkVersion: "3"

package:
  patterns:
    - "!node_modules/**"

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi: "*"
